version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: evangelism-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: evangelism_db
      MYSQL_USER: evangelism_user
      MYSQL_PASSWORD: evangelism_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d
    networks:
      - evangelism-network

  backend:
    build: ./backend
    container_name: evangelism-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: mysql://evangelism_user:evangelism_password@mysql:3306/evangelism_db
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      OPENAI_API_KEY: sk-proj-your-openai-api-key-here
      ZOOM_API_KEY: your-zoom-api-key
      ZOOM_API_SECRET: your-zoom-api-secret
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASS: your-app-password
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql
    networks:
      - evangelism-network

  frontend:
    build: ./frontend
    container_name: evangelism-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - evangelism-network

volumes:
  mysql_data:

networks:
  evangelism-network:
    driver: bridge
